# Site settings
title: "Hudson Bailey"
description: ∆

author: Hudson Bailey
#email:
#twitter_username:
github_username: "hdb"
linkedin_username: "hudsondiggsbailey"

url: "hbd.github.io"

google_analytics_id: UA-170151544-1

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]
