# Site settings
title: "Hudson Bailey"
#description: > 
#  Write a description of your website here.

author: Hudson Bailey
#email:
#twitter_username:
github_username: "hdb"
linkedin_username: "hudsondiggsbailey"

url: "hbd.github.io"

google_analytics_id: UA-170151544-1
#disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]
